### ISSUE TITLE
Log In/Register not working

### ISSUE THREAD

**Issue by anselmlong** [NhatMinh0208/timetable-together#29]
Hello! We tried to access your app, but registering with any account results in a server side error.
![image](https://github.com/NhatMinh0208/timetable-together/assets/85387081/5e4c5763-d484-4d28-a480-9e1af6fc9f35)
But the rest of your app looks pretty cool!! Keep it up :D

**Comment by keyansheng** [comment]
The database was not running at that time.

We should improve the error message though.
